Make scippbuildtools work with other repos
scipp/scippbuildtools pull request #1
Opened 2021-08-23 19:12 UTC by nvaytet

2021-08-25 18:17 UTC, OwenArnold commented on conda/meta.yaml
> +  version: 0.0.1
Why use hard-coded versions rather than tags?

2021-08-25 22:44 UTC, nvaytet commented on conda/meta.yaml
> +  version: 0.0.1
Because until there is a release made, the git tag variables don't seem to work.

2021-08-26 09:39 UTC, OwenArnold commented on conda/meta.yaml
> +  version: 0.0.1
You would just need to create a 0.0.1 tag from main.

2021-08-26 10:53 UTC, nvaytet commented on conda/meta.yaml
> +  version: 0.0.1
Yes that's the plan, but I'll do it once I've finalized everything

2021-08-27 07:04 UTC, OwenArnold requested changes
Basically looks good.

Could you extend the README on the repo to better explain what this is doing and how it fits into the ecosystem?

2021-08-27 07:04 UTC, OwenArnold commented on .azure_pipelines/main.yml
> +    ref: add_build_docs_option
Upstream feature branch now merged into main

2021-08-27 19:35 UTC, merged